#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-ZH-HanDetect
version:      0.04
version_from: HanDetect.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
